# -----------------------------------------------------------------------------
# OUTPUT (root)

/gate/output/root/enable
/gate/output/root/setFileName {OUTPUT_FOLDER}/listmode
/gate/output/root/setRootSinglesAdderFlag 1
#/gate/output/root/setRootSinglesBlurringFlag 1
#/gate/output/root/setRootSinglesSpblurringFlag 1
/gate/output/root/setRootSinglesThresholderFlag 1
/gate/output/root/setRootSinglesUpholderFlag 1
/gate/output/root/setRootHitFlag 0
