# -----------------------------------------------------------------------------
# SPECT


# Need at least 28 Radius to avoid collision at 90 degrees
/control/execute mac/spect_fake_head.mac
/control/execute mac/nm670/spect_translation.mac
/control/execute mac/nm670/spect_rotation.mac
/control/execute mac/spect_detector_input_plane_{COLLIMATOR}.mac

/gate/SPECThead/placement/setTranslation 0. 0. {TRANSLATION} cm
/gate/SPECThead/moves/insert         orbiting
/gate/SPECThead/orbiting/setSpeed    {SPEED} deg/s
/gate/SPECThead/orbiting/setPoint1   0 0 0 cm
/gate/SPECThead/orbiting/setPoint2   0 1 0 cm



# Repeat : two heads
/gate/SPECThead/repeaters/insert ring
/gate/SPECThead/ring/combineWithRotationFirst true
/gate/SPECThead/ring/setRepeatNumber {HEAD_NB}
/gate/SPECThead/ring/setPoint1 0 0 0
/gate/SPECThead/ring/setPoint2 0 0 1
